name: dw_northwind_metabase
version: 1.0.0
config-version: 2

profile: dw_northwind_metabase

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
packages-install-path: "packages"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dw_northwind_metabase:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: view
      +schema: stg
    dw:
      +materialized: table
      +schema: dw
    marts:
      dm_sales:
        +materialized: view
        +schema: dm_sales
      dm_b2b:
        +materialized: view
        +schema: dm_b2b
      dm_b2c:
        +materialized: view
        +schema: dm_b2c
      dm_saas:
        +materialized: view
        +schema: dm_saas
      dm_product_analytics:
        +materialized: view
        +schema: dm_product_analytics

snapshots:
  dw_northwind_metabase:
    +schema: snapshots

vars:
  # Data de corte para a Carga Inicial.
  # Registros criados antes desta data ser?o retroagidos para 1900-01-01.
  # Registros criados depois desta data manter?o sua data real de entrada.
  data_hora_carga_inicial: '2025-11-23 00:00:00'
