dw_northwind_metabase:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5433
      user: postgres
      password: "{{ env_var('DBT_PG_PASSWORD', '123456') }}"
      dbname: dw_northwind_metabase
      schema: dw
