version: 2

sources:
  - name: northwind
    description: "Base operacional Northwind (B2B) exposta no schema public do DW (via FDW ou cópia)."
    schema: public
    tables:
      - name: customer
        description: "Clientes corporativos Northwind."
      - name: salesorder
        description: "Pedidos B2B."
      - name: orderdetail
        description: "Itens dos pedidos."
      - name: product
        description: "Catálogo de produtos Northwind."
      - name: category
        description: "Categorias dos produtos."
      - name: supplier
        description: "Fornecedores Northwind."
      - name: employee
        description: "Colaboradores/força de vendas Northwind."
  - name: metabase
    description: "Base operacional Metabase Sample (B2C/SaaS) exposta no schema public do DW."
    schema: public
    tables:
      - name: accounts
        description: "Contas/clientes SaaS."
      - name: orders
        description: "Pedidos/assinaturas B2C."
      - name: products
        description: "Catálogo de produtos digitais."
      - name: people
        description: "Dados demográficos usados por alguns pedidos B2C."
      - name: invoices
        description: "Receitas recorrentes / faturas SaaS."
      - name: feedback
        description: "Feedbacks textuais coletados via suporte."
      - name: reviews
        description: "Avaliações públicas dos produtos."
      - name: analyticevents
        description: "Eventos de produto/app para analytics."

models:
  - name: stg_northwind_customers
    description: "View de staging para clientes Northwind com NK padronizada."
    columns:
      - name: customer_nk
        tests: [not_null, unique]
      - name: customer_name
        tests: [not_null]
  - name: stg_northwind_orders
    description: "View de staging de pedidos Northwind (cabeçalho)."
    columns:
      - name: order_nk
        tests: [not_null, unique]
      - name: customer_nk
        tests: [not_null]
  - name: stg_northwind_order_details
    description: "Itens de pedido Northwind tratados para métricas de venda."
    columns:
      - name: order_nk
        tests: [not_null]
      - name: product_nk
        tests: [not_null]
  - name: stg_metabase_accounts
    description: "Contas/metadados de clientes Metabase com atributos SaaS."
    columns:
      - name: customer_nk
        tests: [not_null, unique]
  - name: stg_metabase_orders
    description: "Pedidos Metabase com chaves naturais e métricas."
    columns:
      - name: order_nk
        tests: [not_null, unique]
      - name: customer_nk
        tests: [not_null]
  - name: stg_northwind_employees
    description: "Staging da força de vendas Northwind (dimensão de funcionários)."
    columns:
      - name: employee_nk
        tests: [not_null, unique]
  - name: stg_metabase_invoices
    description: "Faturas SaaS com valores financeiros normalizados."
    columns:
      - name: invoice_nk
        tests: [not_null, unique]
      - name: customer_nk
        tests: [not_null]
  - name: stg_metabase_feedback
    description: "Feedbacks textuais com notas e vínculo ao cliente."
    columns:
      - name: feedback_nk
        tests: [not_null, unique]
  - name: stg_metabase_reviews
    description: "Reviews públicos com popularidade do produto."
    columns:
      - name: review_nk
        tests: [not_null, unique]
      - name: product_nk
        tests: [not_null]
  - name: stg_metabase_analytic_events
    description: "Eventos de produto (app/web) com time series."
    columns:
      - name: event_nk
        tests: [not_null, unique]
  - name: stg_metabase_people
    description: "Cadastro de pessoas usado para pedidos B2C sem conta formal."
    columns:
      - name: customer_nk
        tests: [not_null, unique]
  - name: stg_northwind_suppliers
    description: "Fornecedores Northwind com NK padronizada."
    columns:
      - name: supplier_nk
        tests: [not_null, unique]
  - name: stg_northwind_categories
    description: "Categorias Northwind com NK padronizada."
    columns:
      - name: category_nk
        tests: [not_null, unique]
  - name: stg_northwind_products
    description: "Catálogo Northwind padronizado com chaves de fornecedor e categoria."
    columns:
      - name: product_nk
        tests: [not_null, unique]
  - name: stg_metabase_products
    description: "Catálogo Metabase Sample com vendor/category padronizados."
    columns:
      - name: product_nk
        tests: [not_null, unique]
